---
  name-template: "v$RESOLVED_VERSION"
  tag-template: "v$RESOLVED_VERSION"
  categories: # categorize
    - title: "🚀 Feature"
      labels:
        - "enhancement"
    - title: "🐛 Bug Fix"
      labels:
        - "bug"
    - title: "📖 ドキュメント"
      labels:
        - "documentation"
  change-template: "- $TITLE @$AUTHOR (#$NUMBER)"
  change-title-escapes: '\<*_&' # You can add # and @ to disable mentions, and add ` to disable code blocks.
  autolabeler: # auto add labels based on branches or titles
    - label: "enhancement"
      branch:
        - '/feature\/.+/'
        - '/feat\/.+/'
      branch:
        - '/refactor\/.+/'
      title:
        - "/refactor/i"
    - label: "bug"
      branch:
        - '/fix\/.+/'
        - '/bug\/.+/'
      title:
        - "/fix/i"
        - "/bug/i"
    - label: "documentation"
      branch:
        - '/doc\/.+/'
      title:
        - "/doc/i"
  version-resolver: # resolve next version based on tags ($RESOLVED_VERSION)
    major:
      labels:
        - "breaking"
    minor:
      labels:
        - "enhancement"
    default: patch
  template: |
    ## 変更
  
    $CHANGES
  